//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string StreetName { get; set; }
        public string SuburbName { get; set; }
        public Nullable<short> PostalCode { get; set; }
        public string PostalAddress { get; set; }
        public string PostalAddressNumber { get; set; }
        public string PostalAddressSuburbName { get; set; }
        public Nullable<short> PostalAddressCode { get; set; }
        public string HouseNumber { get; set; }
        public string BuildingName { get; set; }
        public int TraineeId { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    
        public virtual Trainee Trainee { get; set; }
    }
}
