//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> ErrorLine { get; set; }
        public Nullable<int> ErrorNumber { get; set; }
        public string ErrorMessage { get; set; }
        public string ErrorProcedure { get; set; }
        public Nullable<int> ErrorSeverity { get; set; }
    }
}
