//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int Id { get; set; }
        public int TraineeId { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string CurrentPosition { get; set; }
        public string EducationSector { get; set; }
        public int Status { get; set; }
        public System.DateTime DateCreate { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Trainee Trainee { get; set; }
    }
}
