//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersPosition
    {
        public int Id { get; set; }
        public Nullable<int> PartnersId { get; set; }
        public Nullable<int> PositionId { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Position Position { get; set; }
    }
}
