//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResetPassword
    {
        public int Id { get; set; }
        public string ASPNetUserId { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public bool Expired { get; set; }
        public int Code { get; set; }
    
        public virtual ResetPassword ResetPassword1 { get; set; }
        public virtual ResetPassword ResetPassword2 { get; set; }
    }
}
