//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Personal_Details
    {
        public Nullable<double> PERSALNO { get; set; }
        public string SURNAME { get; set; }
        public string INITIALS { get; set; }
        public string FIRSTNAMES { get; set; }
        public string RACE { get; set; }
        public string GENDER { get; set; }
        public Nullable<double> SALARY_LEVEL__EMPLOYEE { get; set; }
        public string PAY_POINT_DESCR { get; set; }
        public string IDNUMBER { get; set; }
        public Nullable<double> AGE { get; set; }
        public string DISABILITY { get; set; }
        public string REGION_DESCRIPTION { get; set; }
        public string NATIONALITY_DESCRIPTION { get; set; }
        public string DISTRICT { get; set; }
        public string POST_TYPE { get; set; }
        public string POST_CLASS_DESCR { get; set; }
    }
}
