//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherPosition1
    {
        public int Id { get; set; }
        public string IDNUMBER { get; set; }
        public Nullable<double> POSITION { get; set; }
        public string NAME { get; set; }
    }
}
