//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingSchedule()
        {
            this.Enrolls = new HashSet<Enroll>();
            this.VenueSchedules = new HashSet<VenueSchedule>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TrainingId { get; set; }
        public short StartHour { get; set; }
        public short StartMinutes { get; set; }
        public short EndHour { get; set; }
        public short EndMinutes { get; set; }
        public int VenueId { get; set; }
        public int StatusId { get; set; }
        public Nullable<double> Duration { get; set; }
        public string RelatedTo { get; set; }
        public string InstructorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll> Enrolls { get; set; }
        public virtual Status Status { get; set; }
        public virtual Training Training { get; set; }
        public virtual Venue Venue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VenueSchedule> VenueSchedules { get; set; }
    }
}
