//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Addresses = new HashSet<Address>();
            this.Enrolls = new HashSet<Enroll>();
            this.Experiences = new HashSet<Experience>();
            this.Qualifications = new HashSet<Qualification>();
            this.TraineeGradeSubjects = new HashSet<TraineeGradeSubject>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string IdNumber { get; set; }
        public int PersalNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Title { get; set; }
        public string Initials { get; set; }
        public string Gender { get; set; }
        public string DateOfBirth { get; set; }
        public Nullable<short> Age { get; set; }
        public Nullable<short> Race { get; set; }
        public Nullable<short> Language { get; set; }
        public string CellPhoneNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> SACENumber { get; set; }
        public Nullable<int> Disability { get; set; }
        public Nullable<int> DisabilityType { get; set; }
        public Nullable<short> Levels { get; set; }
        public int PositionId { get; set; }
        public string ASPNETUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enroll> Enrolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Experience> Experiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qualification> Qualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraineeGradeSubject> TraineeGradeSubjects { get; set; }
    }
}
