//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraineeGradeSubject
    {
        public int Id { get; set; }
        public int TraineeId { get; set; }
        public Nullable<int> SubjectGradeId { get; set; }
    
        public virtual GradeSubject GradeSubject { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
