//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string IdNumber { get; set; }
        public string PersalNumber { get; set; }
        public int Title { get; set; }
        public string Initials { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Gender { get; set; }
        public string EmailAddress { get; set; }
        public string Cellphone { get; set; }
        public Nullable<int> PositionId { get; set; }
        public int LevelId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string AspnetUserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdatedBy { get; set; }
        public bool Deleted { get; set; }
        public string TelephoneNumber { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<short> Language { get; set; }
        public Nullable<short> Race { get; set; }
        public Nullable<int> Disability { get; set; }
        public Nullable<int> DisabilityType { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Level Level { get; set; }
        public virtual Position Position { get; set; }
    }
}
