//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueSchedule
    {
        public int Id { get; set; }
        public int VenueId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TrainingScheduleId { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual TrainingSchedule TrainingSchedule { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
