//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassInformation()
        {
            this.SchoolDisifectors = new HashSet<SchoolDisifector>();
        }
    
        public int ID { get; set; }
        public bool DoesTheSchoolPlatoon { get; set; }
        public bool DoesTheSchoolHaveDoubleShifts { get; set; }
        public bool DoesTheSchoolHaveMultiGradeclasses { get; set; }
        public int NoOfLearnersAccommodatedForDailyRotation { get; set; }
        public int NoOfLearnersAccommodatedForWeeklyRotation { get; set; }
        public int NoOfLearnersAccommodatedForHybrid { get; set; }
        public int LearnerCapacityOfSchoolNormsAndStandardForSchoolInfrastructure { get; set; }
        public bool HasTheSchoolAdjustedTheSchoolDayToCoverTheRegulatedHoursForCurriculumDelivery { get; set; }
        public Nullable<double> TotalTeachingTimeOverTheCycle { get; set; }
        public bool WereAdditionalMobileClassroomsRequestedByTheSchool { get; set; }
        public int NoOfMobileClassroomsRequestedByTheSchool { get; set; }
        public int NoOfAdditionalMobileClassroomsDelivered { get; set; }
        public int NoOfClassroomsNotUsedDueToPoorCondition { get; set; }
        public Nullable<bool> WasTheSchoolClosedDueToCovid19 { get; set; }
        public int NoOfOccasionsTheSchoolClosedDueToCovid19 { get; set; }
        public int LongestDurationTheSchoolClosedDueToCovid19 { get; set; }
        public bool WasTheSchoolDisinfected { get; set; }
        public int SchoolID { get; set; }
        public System.DateTime DateLogged { get; set; }
        public Nullable<int> IntroducedRotationID { get; set; }
        public Nullable<int> TimetableCycleID { get; set; }
        public Nullable<int> SchoolRotationApproachID { get; set; }
        public Nullable<int> WasTheSchoolAbleToAccommodatePhysicalDistancingID { get; set; }
    
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolDisifector> SchoolDisifectors { get; set; }
    }
}
