//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculumDelivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CurriculumDelivery()
        {
            this.CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection = new HashSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection>();
            this.CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020 = new HashSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020>();
            this.CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020 = new HashSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020>();
            this.CurriculumDelivery_ApprovedSubjects = new HashSet<CurriculumDelivery_ApprovedSubjects>();
            this.CurriculumDelivery_DistrictSupportRecievedForLockdownLearning = new HashSet<CurriculumDelivery_DistrictSupportRecievedForLockdownLearning>();
            this.CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren = new HashSet<CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren>();
            this.CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks = new HashSet<CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks>();
            this.CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme = new HashSet<CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme>();
            this.CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme = new HashSet<CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme>();
            this.CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme = new HashSet<CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme>();
            this.CurriculumDelivery_LaggingBehindSchoolIntervention = new HashSet<CurriculumDelivery_LaggingBehindSchoolIntervention>();
            this.CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning = new HashSet<CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning>();
            this.CurriculumDelivery_ReachedGradesDuringLockdonLevel5 = new HashSet<CurriculumDelivery_ReachedGradesDuringLockdonLevel5>();
            this.CurriculumDelivery_SeniorPhaseInitiatives = new HashSet<CurriculumDelivery_SeniorPhaseInitiatives>();
            this.CurriculumDelivery_SubjectAdvisorsSupportedTheStaff = new HashSet<CurriculumDelivery_SubjectAdvisorsSupportedTheStaff>();
            this.CurriculumDelivery_TeacherDevicesAreReliantOn = new HashSet<CurriculumDelivery_TeacherDevicesAreReliantOn>();
            this.CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020 = new HashSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020>();
            this.CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum = new HashSet<CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum>();
        }
    
        public int ID { get; set; }
        public bool WasTheSchoolAbleToDeliverLessonsToLearnersDuringLockdownLevel5 { get; set; }
        public Nullable<int> OnlineWithStudentTeacherInteractionID { get; set; }
        public Nullable<int> OnlineWithoutStudentTeacherInteractionID { get; set; }
        public Nullable<int> TVBasedLessonsAndProgrammesID { get; set; }
        public Nullable<int> RadioLearningProgrammesID { get; set; }
        public Nullable<int> SocialMediaForStudentTeacherInteractionID { get; set; }
        public Nullable<int> PaperBasedPackagesID { get; set; }
        public Nullable<int> HomeVisitsByTeachersID { get; set; }
        public Nullable<int> UseOfExternalServiceProvidersID { get; set; }
        public string OtherDistanceLearningDescription { get; set; }
        public Nullable<int> OtherDistanceLearningID { get; set; }
        public int DevicesUtilisedByEducatorsUseID { get; set; }
        public bool DidTheSchoolProvideEducatorsWithDataToEnableWiFiConnectivityWhenWorkingFromHome { get; set; }
        public int NoOfEducatorsTrainedToConductOnlineClasses { get; set; }
        public int NoOfEducatorsNotTrainedToConductOnlineClasses { get; set; }
        public int NoOfEducatorsSuccessfullyConductedOnlineClasses { get; set; }
        public bool WasTerm1OfTheATPCompleted { get; set; }
        public bool WasTerm1AssessmentCompleted { get; set; }
        public bool WereTerm1ReportCardsIssued { get; set; }
        public bool IsTheSchoolImplementingTheRevisedATP { get; set; }
        public bool HaSchoolCommunicatedWithParentsRegardingAssessmentTasksExpectedFromLearners { get; set; }
        public bool HasSchoolReceivedFortnightlyLearnerActivityPacks { get; set; }
        public bool HasTheSchoolProvidedTheirOwnResourcesToFacilitateLockdownLearning { get; set; }
        public bool HaveParentsPickedUpTheFortnightlyLearnerActivityPacks { get; set; }
        public bool HasTheSchoolFollowedUpWithTheParentsOfLearnersThatFailedToSubmitTheirLearningTasks { get; set; }
        public bool AreTheLearnersAttendingClassAtSchoolAndThoseAtHomeAtTheSameLevelOfCompletion { get; set; }
        public bool DoesTheSchoolEnsureThatTheParentsSubmitTheirChildrenAssessmentTasksInTime { get; set; }
        public int NoOfLearnersBenefittedFromTheHomeLearningPacks { get; set; }
        public Nullable<int> CompletedRequiredNofAssesmentsGrade1To3ID { get; set; }
        public Nullable<int> CompletedRequiredNofAssesmentsGrade4To9ID { get; set; }
        public Nullable<int> CompletedRequiredNofAssesmentsGrade10To11ID { get; set; }
        public Nullable<int> CompletedRequiredNofAssesmentsGrade12ID { get; set; }
        public bool WillTheSchoolHaveCompletedTheGrade12ProgrammeInAdvanceOfThePrelimExaminations { get; set; }
        public string ReasonForNotCompletingTheGrade12ProgrammeInAdvanceOfThePrelimExaminations { get; set; }
        public int SchoolID { get; set; }
        public System.DateTime DateLogged { get; set; }
        public string SubjectAdvisorsSupportedTheStaffOther { get; set; }
        public string LaggingBehindSchoolInterventionsOther { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection> CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020> CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020> CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_ApprovedSubjects> CurriculumDelivery_ApprovedSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_DistrictSupportRecievedForLockdownLearning> CurriculumDelivery_DistrictSupportRecievedForLockdownLearning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren> CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks> CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme> CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme> CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme> CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_LaggingBehindSchoolIntervention> CurriculumDelivery_LaggingBehindSchoolIntervention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning> CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_ReachedGradesDuringLockdonLevel5> CurriculumDelivery_ReachedGradesDuringLockdonLevel5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_SeniorPhaseInitiatives> CurriculumDelivery_SeniorPhaseInitiatives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_SubjectAdvisorsSupportedTheStaff> CurriculumDelivery_SubjectAdvisorsSupportedTheStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_TeacherDevicesAreReliantOn> CurriculumDelivery_TeacherDevicesAreReliantOn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020> CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum> CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum { get; set; }
        public virtual School School { get; set; }
    }
}
