//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducatorsResourcesDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EducatorsResourcesDetail()
        {
            this.EducatorDevicesReliantOns = new HashSet<EducatorDevicesReliantOn>();
            this.SchoolInformParentsAboutChildrenPerformances = new HashSet<SchoolInformParentsAboutChildrenPerformance>();
            this.SeniorPhaseGradesApplications = new HashSet<SeniorPhaseGradesApplication>();
            this.SubjectObtainedApprovals = new HashSet<SubjectObtainedApproval>();
            this.UseOfDevicesUtilisedByEducators = new HashSet<UseOfDevicesUtilisedByEducator>();
        }
    
        public int ID { get; set; }
        public bool DidTheSchoolProvideEducatorsWithData { get; set; }
        public int NoOfEducatorTrainedToUseOnlineSolution { get; set; }
        public int NoOfEducatorNotTrainedToUseOnlineSolution { get; set; }
        public int NoOfEducatorAbleToUseOnlineSolution { get; set; }
        public bool WasQ1Term1OfTheATPcompleted { get; set; }
        public bool WasTheQ1Term1AssessmentCompleted { get; set; }
        public bool WereQ1Term1ReportCardsIssued { get; set; }
        public bool IsTheSchoolImplementingTheRevisedATP { get; set; }
        public bool AreTheLearnersAttendingClassAtSchoolAndThoseAtHomeAtTheSameLevelOfCompletion { get; set; }
        public bool DoesTheSchoolEnsureThatTheParentsSubmitTheirChildrensAssessmentOnTime { get; set; }
        public int NoOfLearnersBenefittedFromHomeLearningPacksFromSchool { get; set; }
        public bool WillTheSchoolHaveCompletedTheGrade12ProgrammeInAdvanceOfPrelimExaminations { get; set; }
        public string ReasonForNotCompletingTheGrade12ProgrammeInAdvanceOfPrelimExaminations { get; set; }
        public int SchoolID { get; set; }
        public System.DateTime DateLogged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducatorDevicesReliantOn> EducatorDevicesReliantOns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolInformParentsAboutChildrenPerformance> SchoolInformParentsAboutChildrenPerformances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeniorPhaseGradesApplication> SeniorPhaseGradesApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectObtainedApproval> SubjectObtainedApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UseOfDevicesUtilisedByEducator> UseOfDevicesUtilisedByEducators { get; set; }
        public virtual School School { get; set; }
    }
}
