//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducatorResource
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public int ProvidedByGDE { get; set; }
        public int ProvidedBySchool { get; set; }
        public int PersonallyOwned { get; set; }
        public int SchoolID { get; set; }
        public System.DateTime DateLogged { get; set; }
    
        public virtual School School { get; set; }
    }
}
