//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Finance()
        {
            this.FinanceSchoolFeeDefaulters = new HashSet<FinanceSchoolFeeDefaulter>();
            this.FinanceSchoolShortfallOptions = new HashSet<FinanceSchoolShortfallOption>();
        }
    
        public int ID { get; set; }
        public int SchoolTypeID { get; set; }
        public bool IsTheSchoolProjectingShortfallInRevenue { get; set; }
        public int NoOfLearnersApprovedForSchoolFeeExemptionsConditional2019 { get; set; }
        public int NoOfLearnersApprovedForSchoolFeeExemptionsConditional2020 { get; set; }
        public int NoOfLearnersApprovedForSchoolFeeExemptionsPartial2019 { get; set; }
        public int NoOfLearnersApprovedForSchoolFeeExemptionsPartial2020 { get; set; }
        public int NoOfLearnersApprovedForSchoolFeeExemptionsTotal2019 { get; set; }
        public int NoOfLearnersApprovedForSchoolFeeExemptionsTotal2020 { get; set; }
        public int NoOfLearnersApprovedPostLockdownConditional { get; set; }
        public int NoOfLearnersApprovedPostLockdownPartial { get; set; }
        public int NoOfLearnersApprovedPostLockdownTotal { get; set; }
        public int NoOfLearnersWhoseParentsDefaultedOnSchoolFeePayments2019 { get; set; }
        public int NoOfLearnersWhoseParentsDefaultedOnSchoolFeePayments2020 { get; set; }
        public string HowDidTheReducedRevenueCollectionImpactOnOperations { get; set; }
        public bool DidYouContinueWithSection38APaymentsToStaff { get; set; }
        public string HowDidTheSchoolManagePayments { get; set; }
        public bool CanTheSchoolConfirmThatLTSMHasBeenProcuredFor2021 { get; set; }
        public bool CanTheSchoolConfirmThatItHasBeenAbleToPayTheirMunicipalAccounts { get; set; }
        public bool CanTheSchoolConfirmThatItHasBeenAbleToUndertakeMinorRepairsUsingTheMaintenanceBudget { get; set; }
        public bool CanTheSchoolConfirmThatTheyHavePaidAllTheirSGBAppointedStaff { get; set; }
        public bool DidTheSchoolRelieveSGBAppointedTeachingStaffOfTheirDuties { get; set; }
        public Nullable<int> NoOfSGBAppointedTeachingStaffWereAffected { get; set; }
        public bool WasTheReprioritisedBudgetApprovedAtAnAGM { get; set; }
        public bool DidTheInitiativesPursuedAssistTheSchoolInRealisingTheBudgetRevenueShortfall { get; set; }
        public bool IsThisSchoolSubsidisedByTheState { get; set; }
        public string WhatAreTheMainSourcesOfRevenueForTheSchool { get; set; }
        public bool IsTheSchoolProjectingShortfallInRevenueCollectionFor2020 { get; set; }
        public bool HaveYouPurchasedAdditionalLearnerAndEducatorSupportMaterial { get; set; }
        public bool DoesTheSchoolHaveSufficientTextbooksForAllTheLearners { get; set; }
        public bool WasTheSchoolAbleToPayTheirMunicipalAccounts { get; set; }
        public bool WasTheSchoolAbleToPurchasePPEsAndCovid19RelatedSupplies { get; set; }
        public bool DidTheSchoolRelieveTeachingStaffOfTheirDutiesToBalanceTheBudget { get; set; }
        public int HowManyTeachingStaffWereRelievedOfTheirDutiesToBalanceTheBudget { get; set; }
        public int SchoolID { get; set; }
        public System.DateTime DateLogged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceSchoolFeeDefaulter> FinanceSchoolFeeDefaulters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinanceSchoolShortfallOption> FinanceSchoolShortfallOptions { get; set; }
        public virtual School School { get; set; }
    }
}
