//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelBoarder
    {
        public int ID { get; set; }
        public int NoOfLearnersAdmittedToTheHostelInJanuary2020Male { get; set; }
        public int NoOfLearnersAdmittedToTheHostelInJanuary2020Female { get; set; }
        public bool DidTheSchoolApplyTheRelevantPhysicalDistancingMealTime { get; set; }
        public bool DidTheSchoolApplyTheRelevantPhysicalDistancingStudyTime { get; set; }
        public bool DidTheSchoolApplyTheRelevantPhysicalDistancingLeisureTime { get; set; }
        public bool DidTheSchoolIncreaseTheFrequencyOfCleaningAtTheHostel { get; set; }
        public bool WereTheLearnersProvidedWithAdequatePPEs { get; set; }
        public bool WereTheLearnersProvidedWithAdequateHandSanitiser { get; set; }
        public int SchoolID { get; set; }
        public System.DateTime DateLogged { get; set; }
    
        public virtual School School { get; set; }
    }
}
