//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearnerInformationByCategory
    {
        public int ID { get; set; }
        public int HeadcountEnrolment { get; set; }
        public int CurrentEnrolment { get; set; }
        public int NoOfLearnersAttendingClassesAtSchoolCurrently { get; set; }
        public int NoOfLearnersStudyingFromHomeCurrently { get; set; }
        public int NoOfLearnersDeregisteredFromTheSchoolAndApprovedForHomeEducation { get; set; }
        public int NoOfLearnersThatHavePotentiallyDroppedOutOfSchool { get; set; }
        public int NoOfLearnersTransferredIntoTheSchool { get; set; }
        public int NoOfLearnersTransferredOutToOtherSchools { get; set; }
        public string Grade { get; set; }
        public int SchoolID { get; set; }
    
        public virtual School School { get; set; }
    }
}
