//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookupItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LookupItem()
        {
            this.AvailedOptionsToSupportGrade12 = new HashSet<AvailedOptionsToSupportGrade12>();
            this.CoveredGradeFundamentals = new HashSet<CoveredGradeFundamental>();
            this.DistrictLockdownLearningSupports = new HashSet<DistrictLockdownLearningSupport>();
            this.EducatorDevicesReliantOns = new HashSet<EducatorDevicesReliantOn>();
            this.GradesCompleteRequiredAssessmentTasks = new HashSet<GradesCompleteRequiredAssessmentTask>();
            this.LaggingBehindSchoolInterventions = new HashSet<LaggingBehindSchoolIntervention>();
            this.LockdownLearningDetails = new HashSet<LockdownLearningDetail>();
            this.ParentsAndLearnersGuidences = new HashSet<ParentsAndLearnersGuidence>();
            this.SchoolAdjustmentsToConforms = new HashSet<SchoolAdjustmentsToConform>();
            this.SchoolConformOptions = new HashSet<SchoolConformOption>();
            this.SchoolDisruptionsCauses = new HashSet<SchoolDisruptionsCaus>();
            this.SchoolForcedClosureReasons = new HashSet<SchoolForcedClosureReason>();
            this.SchoolInformParentsAboutChildrenPerformances = new HashSet<SchoolInformParentsAboutChildrenPerformance>();
            this.SchoolLockdownLearnersAssistances = new HashSet<SchoolLockdownLearnersAssistance>();
            this.SchoolNutritionChallengeResponses = new HashSet<SchoolNutritionChallengeRespons>();
            this.SchoolRequirementsToComplyWithCovid19 = new HashSet<SchoolRequirementsToComplyWithCovid19>();
            this.SchoolTransportChallengeResponses = new HashSet<SchoolTransportChallengeRespons>();
            this.SeniorPhaseGradesApplications = new HashSet<SeniorPhaseGradesApplication>();
            this.SubjectObtainedApprovals = new HashSet<SubjectObtainedApproval>();
            this.UseOfDevicesUtilisedByEducators = new HashSet<UseOfDevicesUtilisedByEducator>();
            this.SchoolDisifectors = new HashSet<SchoolDisifector>();
            this.ClassInformation_NonRotatingGrades = new HashSet<ClassInformation_NonRotatingGrades>();
            this.CurriculumDelivery_ApprovedSubjects = new HashSet<CurriculumDelivery_ApprovedSubjects>();
            this.CurriculumDelivery_DistrictSupportRecievedForLockdownLearning = new HashSet<CurriculumDelivery_DistrictSupportRecievedForLockdownLearning>();
            this.CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren = new HashSet<CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren>();
            this.CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks = new HashSet<CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks>();
            this.CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme = new HashSet<CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme>();
            this.CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme = new HashSet<CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme>();
            this.CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme = new HashSet<CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme>();
            this.CurriculumDelivery_LaggingBehindSchoolIntervention = new HashSet<CurriculumDelivery_LaggingBehindSchoolIntervention>();
            this.CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning = new HashSet<CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning>();
            this.CurriculumDelivery_ReachedGradesDuringLockdonLevel5 = new HashSet<CurriculumDelivery_ReachedGradesDuringLockdonLevel5>();
            this.CurriculumDelivery_SeniorPhaseInitiatives = new HashSet<CurriculumDelivery_SeniorPhaseInitiatives>();
            this.CurriculumDelivery_SubjectAdvisorsSupportedTheStaff = new HashSet<CurriculumDelivery_SubjectAdvisorsSupportedTheStaff>();
            this.CurriculumDelivery_TeacherDevicesAreReliantOn = new HashSet<CurriculumDelivery_TeacherDevicesAreReliantOn>();
            this.Grade12LevelOfCompletion = new HashSet<Grade12LevelOfCompletion>();
            this.CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection = new HashSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection>();
            this.CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020 = new HashSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020>();
            this.CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020 = new HashSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020>();
            this.EnablingConditions_CausesOfDisruptions = new HashSet<EnablingConditions_CausesOfDisruptions>();
            this.EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsClassrooms = new HashSet<EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsClassrooms>();
            this.EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsFurniture = new HashSet<EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsFurniture>();
            this.EnablingConditions_ReasonsForSchoolClosure = new HashSet<EnablingConditions_ReasonsForSchoolClosure>();
            this.EnablingConditions_SchoolRequirementsToComplyWithPhysicalDistance = new HashSet<EnablingConditions_SchoolRequirementsToComplyWithPhysicalDistance>();
            this.EnablingConditions_SchoolResponsesToLearnerTransportProgrammeChallenges = new HashSet<EnablingConditions_SchoolResponsesToLearnerTransportProgrammeChallenges>();
            this.EnablingConditions_SchoolResponsesToNutritionProgrammeChallenges = new HashSet<EnablingConditions_SchoolResponsesToNutritionProgrammeChallenges>();
            this.CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020 = new HashSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020>();
            this.CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum = new HashSet<CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum>();
            this.CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum1 = new HashSet<CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum>();
        }
    
        public int ID { get; set; }
        public string Caption { get; set; }
        public int CategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvailedOptionsToSupportGrade12> AvailedOptionsToSupportGrade12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoveredGradeFundamental> CoveredGradeFundamentals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistrictLockdownLearningSupport> DistrictLockdownLearningSupports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducatorDevicesReliantOn> EducatorDevicesReliantOns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GradesCompleteRequiredAssessmentTask> GradesCompleteRequiredAssessmentTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaggingBehindSchoolIntervention> LaggingBehindSchoolInterventions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LockdownLearningDetail> LockdownLearningDetails { get; set; }
        public virtual LookupCategory LookupCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentsAndLearnersGuidence> ParentsAndLearnersGuidences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolAdjustmentsToConform> SchoolAdjustmentsToConforms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolConformOption> SchoolConformOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolDisruptionsCaus> SchoolDisruptionsCauses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolForcedClosureReason> SchoolForcedClosureReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolInformParentsAboutChildrenPerformance> SchoolInformParentsAboutChildrenPerformances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolLockdownLearnersAssistance> SchoolLockdownLearnersAssistances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolNutritionChallengeRespons> SchoolNutritionChallengeResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolRequirementsToComplyWithCovid19> SchoolRequirementsToComplyWithCovid19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolTransportChallengeRespons> SchoolTransportChallengeResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeniorPhaseGradesApplication> SeniorPhaseGradesApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubjectObtainedApproval> SubjectObtainedApprovals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UseOfDevicesUtilisedByEducator> UseOfDevicesUtilisedByEducators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolDisifector> SchoolDisifectors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassInformation_NonRotatingGrades> ClassInformation_NonRotatingGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_ApprovedSubjects> CurriculumDelivery_ApprovedSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_DistrictSupportRecievedForLockdownLearning> CurriculumDelivery_DistrictSupportRecievedForLockdownLearning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren> CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks> CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme> CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme> CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme> CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_LaggingBehindSchoolIntervention> CurriculumDelivery_LaggingBehindSchoolIntervention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning> CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_ReachedGradesDuringLockdonLevel5> CurriculumDelivery_ReachedGradesDuringLockdonLevel5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_SeniorPhaseInitiatives> CurriculumDelivery_SeniorPhaseInitiatives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_SubjectAdvisorsSupportedTheStaff> CurriculumDelivery_SubjectAdvisorsSupportedTheStaff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_TeacherDevicesAreReliantOn> CurriculumDelivery_TeacherDevicesAreReliantOn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade12LevelOfCompletion> Grade12LevelOfCompletion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection> CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020> CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020> CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnablingConditions_CausesOfDisruptions> EnablingConditions_CausesOfDisruptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsClassrooms> EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsClassrooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsFurniture> EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsFurniture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnablingConditions_ReasonsForSchoolClosure> EnablingConditions_ReasonsForSchoolClosure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnablingConditions_SchoolRequirementsToComplyWithPhysicalDistance> EnablingConditions_SchoolRequirementsToComplyWithPhysicalDistance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnablingConditions_SchoolResponsesToLearnerTransportProgrammeChallenges> EnablingConditions_SchoolResponsesToLearnerTransportProgrammeChallenges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnablingConditions_SchoolResponsesToNutritionProgrammeChallenges> EnablingConditions_SchoolResponsesToNutritionProgrammeChallenges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020> CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum> CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum> CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum1 { get; set; }
    }
}
