//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LTSM
    {
        public int ID { get; set; }
        public int Grade1 { get; set; }
        public int Grade2 { get; set; }
        public int Grade3 { get; set; }
        public int Grade4 { get; set; }
        public int Grade5 { get; set; }
        public int Grade6 { get; set; }
        public int Grade7 { get; set; }
        public int Grade8 { get; set; }
        public int Grade9 { get; set; }
        public int Grade10 { get; set; }
        public int Grade11 { get; set; }
        public int Grade12 { get; set; }
        public string Category { get; set; }
        public int SchoolID { get; set; }
        public System.DateTime DateLogged { get; set; }
    
        public virtual School School { get; set; }
    }
}
