//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Covid19ImpactSurveyEntities : DbContext
    {
        public Covid19ImpactSurveyEntities()
            : base("name=Covid19ImpactSurveyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailedOptionsToSupportGrade12> AvailedOptionsToSupportGrade12 { get; set; }
        public virtual DbSet<AverageLearnerAttendenceBetween31AugustAnd11September> AverageLearnerAttendenceBetween31AugustAnd11September { get; set; }
        public virtual DbSet<CoveredGradeFundamental> CoveredGradeFundamentals { get; set; }
        public virtual DbSet<CurriculumDeliveryAcrossTheDiffentLockdownLevel> CurriculumDeliveryAcrossTheDiffentLockdownLevels { get; set; }
        public virtual DbSet<DistrictLockdownLearningSupport> DistrictLockdownLearningSupports { get; set; }
        public virtual DbSet<EducatorDevicesReliantOn> EducatorDevicesReliantOns { get; set; }
        public virtual DbSet<EducatorsResourcesDetail> EducatorsResourcesDetails { get; set; }
        public virtual DbSet<Finance> Finances { get; set; }
        public virtual DbSet<FinanceSchoolFeeDefaulter> FinanceSchoolFeeDefaulters { get; set; }
        public virtual DbSet<FinanceSchoolShortfallOption> FinanceSchoolShortfallOptions { get; set; }
        public virtual DbSet<GradesCompleteRequiredAssessmentTask> GradesCompleteRequiredAssessmentTasks { get; set; }
        public virtual DbSet<LaggingBehindSchoolIntervention> LaggingBehindSchoolInterventions { get; set; }
        public virtual DbSet<LearnerInformationByCategory> LearnerInformationByCategories { get; set; }
        public virtual DbSet<LockdownLearningDetail> LockdownLearningDetails { get; set; }
        public virtual DbSet<LookupCategory> LookupCategories { get; set; }
        public virtual DbSet<LookupItem> LookupItems { get; set; }
        public virtual DbSet<LTSM> LTSMs { get; set; }
        public virtual DbSet<OnlineRemoteAndDistanceLearning> OnlineRemoteAndDistanceLearnings { get; set; }
        public virtual DbSet<ParentsAndLearnersGuidence> ParentsAndLearnersGuidences { get; set; }
        public virtual DbSet<SchoolAdjustmentsToConform> SchoolAdjustmentsToConforms { get; set; }
        public virtual DbSet<SchoolBuildingCondition> SchoolBuildingConditions { get; set; }
        public virtual DbSet<SchoolConformOption> SchoolConformOptions { get; set; }
        public virtual DbSet<SchoolDisruptionsCaus> SchoolDisruptionsCauses { get; set; }
        public virtual DbSet<SchoolForcedClosureReason> SchoolForcedClosureReasons { get; set; }
        public virtual DbSet<SchoolInformParentsAboutChildrenPerformance> SchoolInformParentsAboutChildrenPerformances { get; set; }
        public virtual DbSet<SchoolLockdownLearnersAssistance> SchoolLockdownLearnersAssistances { get; set; }
        public virtual DbSet<SchoolNutritionChallengeRespons> SchoolNutritionChallengeResponses { get; set; }
        public virtual DbSet<SchoolRequirementsToComplyWithCovid19> SchoolRequirementsToComplyWithCovid19 { get; set; }
        public virtual DbSet<SchoolTransportChallengeRespons> SchoolTransportChallengeResponses { get; set; }
        public virtual DbSet<SeniorPhaseGradesApplication> SeniorPhaseGradesApplications { get; set; }
        public virtual DbSet<SubjectObtainedApproval> SubjectObtainedApprovals { get; set; }
        public virtual DbSet<UseOfDevicesUtilisedByEducator> UseOfDevicesUtilisedByEducators { get; set; }
        public virtual DbSet<StaffInformationSMTManagementOfAttendence> StaffInformationSMTManagementOfAttendences { get; set; }
        public virtual DbSet<SchoolDisifector> SchoolDisifectors { get; set; }
        public virtual DbSet<ClassInformation_NonRotatingGrades> ClassInformation_NonRotatingGrades { get; set; }
        public virtual DbSet<ClassInformationDetail> ClassInformationDetails { get; set; }
        public virtual DbSet<SchoolMultiGrade> SchoolMultiGrades { get; set; }
        public virtual DbSet<HostelBoarder> HostelBoarders { get; set; }
        public virtual DbSet<LearnersCovid19StatisticsPerAgeGroup> LearnersCovid19StatisticsPerAgeGroup { get; set; }
        public virtual DbSet<LearnersCovid19StatisticsPerGrade> LearnersCovid19StatisticsPerGrade { get; set; }
        public virtual DbSet<StaffCovid19StatisticsPerAgeGroup> StaffCovid19StatisticsPerAgeGroup { get; set; }
        public virtual DbSet<CurriculumDelivery_ApprovedSubjects> CurriculumDelivery_ApprovedSubjects { get; set; }
        public virtual DbSet<CurriculumDelivery_DistrictSupportRecievedForLockdownLearning> CurriculumDelivery_DistrictSupportRecievedForLockdownLearning { get; set; }
        public virtual DbSet<CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren> CurriculumDelivery_HowDidTheSchoolInformParentsAboutThePerformanceOfTheirChildren { get; set; }
        public virtual DbSet<CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks> CurriculumDelivery_HowHasTheSchoolAssistedLockdownLearnersWithTheirAssessmentTasks { get; set; }
        public virtual DbSet<CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme> CurriculumDelivery_InitiativesAvailedByTheGDEToSupportMatriculantsToCompleteTheGrade12Programme { get; set; }
        public virtual DbSet<CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme> CurriculumDelivery_InitiativesAvailedByThePartnersToSupportMatriculantsToCompleteTheGrade12Programme { get; set; }
        public virtual DbSet<CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme> CurriculumDelivery_InitiativesAvailedByTheSchoolToSupportMatriculantsToCompleteTheGrade12Programme { get; set; }
        public virtual DbSet<CurriculumDelivery_LaggingBehindSchoolIntervention> CurriculumDelivery_LaggingBehindSchoolIntervention { get; set; }
        public virtual DbSet<CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning> CurriculumDelivery_MeansToProvideGuidanceToParentsAndLearnersToFacilitateLockdownLearning { get; set; }
        public virtual DbSet<CurriculumDelivery_ReachedGradesDuringLockdonLevel5> CurriculumDelivery_ReachedGradesDuringLockdonLevel5 { get; set; }
        public virtual DbSet<CurriculumDelivery_SeniorPhaseInitiatives> CurriculumDelivery_SeniorPhaseInitiatives { get; set; }
        public virtual DbSet<CurriculumDelivery_SubjectAdvisorsSupportedTheStaff> CurriculumDelivery_SubjectAdvisorsSupportedTheStaff { get; set; }
        public virtual DbSet<CurriculumDelivery_TeacherDevicesAreReliantOn> CurriculumDelivery_TeacherDevicesAreReliantOn { get; set; }
        public virtual DbSet<Grade12LevelOfCompletion> Grade12LevelOfCompletion { get; set; }
        public virtual DbSet<EducatorResource> EducatorResources { get; set; }
        public virtual DbSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection> CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection { get; set; }
        public virtual DbSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020> CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection02August2020 { get; set; }
        public virtual DbSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020> CurriculumDelivery_AccomodatedGradesFollowingMinistersSetOfDirection07July2020 { get; set; }
        public virtual DbSet<CurriculumDelivery> CurriculumDeliveries { get; set; }
        public virtual DbSet<EnablingConditions_CausesOfDisruptions> EnablingConditions_CausesOfDisruptions { get; set; }
        public virtual DbSet<EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsClassrooms> EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsClassrooms { get; set; }
        public virtual DbSet<EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsFurniture> EnablingConditions_HowDidTheSchoolConformToThePhysicalDistancingRequirementsFurniture { get; set; }
        public virtual DbSet<EnablingConditions_ReasonsForSchoolClosure> EnablingConditions_ReasonsForSchoolClosure { get; set; }
        public virtual DbSet<EnablingConditions_SchoolRequirementsToComplyWithPhysicalDistance> EnablingConditions_SchoolRequirementsToComplyWithPhysicalDistance { get; set; }
        public virtual DbSet<EnablingConditions_SchoolResponsesToLearnerTransportProgrammeChallenges> EnablingConditions_SchoolResponsesToLearnerTransportProgrammeChallenges { get; set; }
        public virtual DbSet<EnablingConditions_SchoolResponsesToNutritionProgrammeChallenges> EnablingConditions_SchoolResponsesToNutritionProgrammeChallenges { get; set; }
        public virtual DbSet<EnablingCondition> EnablingConditions { get; set; }
        public virtual DbSet<CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020> CurriculumDelivery_AccomodatedGradesFollowingMinistersFirstSetOfDirection29June2020 { get; set; }
        public virtual DbSet<LearnerInformation> LearnerInformations { get; set; }
        public virtual DbSet<StaffInformationManagementOfConcession> StaffInformationManagementOfConcessions { get; set; }
        public virtual DbSet<CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum> CurriculumDelivery_ModeOfDeliveryAdoptedByTheSchoolsToDeliverTheCurriculum { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<ClassInformation> ClassInformations { get; set; }
        public virtual DbSet<StaffInformationHeadCount> StaffInformationHeadCounts { get; set; }
    }
}
