//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMultiGrade
    {
        public System.Guid ID { get; set; }
        public int SchoolID { get; set; }
        public int GradeID { get; set; }
    
        public virtual School School { get; set; }
    }
}
