//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSurvey.Pages.Survey
{


    public partial class Survey
    {

        /// <summary>
        /// SqlDataSource15 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource15;

        /// <summary>
        /// hdfTraineeID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdfTraineeID;

        /// <summary>
        /// hdfQualificationId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdfQualificationId;

        /// <summary>
        /// hdfWorkExperienceId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hdfWorkExperienceId;

        /// <summary>
        /// GeneralSchoolInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.GeneralSchoolInformation GeneralSchoolInformation;

        /// <summary>
        /// Guidelines control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.Guidelines Guidelines;

        /// <summary>
        /// LearnerInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.LearnerInformation LearnerInformation;

        /// <summary>
        /// StaffInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.StaffInformation StaffInformation;

        /// <summary>
        /// ClassInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.ClassInformation ClassInformation;

        /// <summary>
        /// FinanceInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.FinanceInformation FinanceInformation;

        /// <summary>
        /// HostelBoardersInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.HostelBoardersInformation HostelBoardersInformation;

        /// <summary>
        /// InfectionsAndMortalityInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.InfectionsAndMortalityInformation InfectionsAndMortalityInformation;

        /// <summary>
        /// CurriculumDeliveryAndCompletion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.CurriculumDeliveryAndCompletion CurriculumDeliveryAndCompletion;

        /// <summary>
        /// EnablingConditions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OnlineSurvey.Pages.Survey.Controls.EnablingConditions EnablingConditions;

        /// <summary>
        /// hdnData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdnData;

        /// <summary>
        /// hdfSchoolID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hdfSchoolID;
    }
}
